---
:concurrency: 1
:queues:
  - default
  - mailers
  - ahoy
:schedule:
  MondayPrepJob:
    description: 'Show users what this new week has in store for them'
    cron: '0 * * * 0' # every hour on Mondays
